### PR TITLE
feat!: preprocess style tags by default

### PR DESCRIPTION
**Pull request by bluwy**
fix https://github.com/sveltejs/vite-plugin-svelte/issues/733

Follow Vite's behavior to preprocess all CSS by default with postcss or lightningcss.

Note: there's a small optimization in Vite where it skips postcss if there's no `@import` and postcss plugins. Lightningcss doesn't seem to have that optimization.

This affects preprocessing in component libraries too, but I think they should only have a small impact.

### CODE REVIEW

**Review by kaisermann — APPROVED** [review]
I guess this is fine too! Repeating what I said in the linked issue: `svelte-preprocess` [will preprocess style blocks without `lang` if the `postcss` configuration is found/valid.](https://github.com/sveltejs/svelte-preprocess/blob/main/src/autoProcess.ts#L237).

**Comment by benmccann** [comment]
My main question is whether language-tools would know to run the preprocessor, so I'd want Simon's approval

**Comment by benmccann** [comment]
@dummdidumm is on vacation, so you might have to ask again later 😄

**Review by dummdidumm — APPROVED** [review]
I'm good with this. The fact that the IDE may give false positives shouldn't hold up this valuable PR - and people can tune their config / add a lang tag if needed. We may also be able to detect some of this inside language tools and don't show CSS errors. And since nested CSS is now part of the spec, the upstream vs code html language service might even support it at some point.

**Review by dominikg — APPROVED** [review]

**Comment by dominikg** [comment]
If people report performance regressions from postcss going all over their files without lang=postcss tag, we can add an option to restore the previous behavior or recommend they switch to lightningcss?

**Pull request merged**
