### PR TITLE
chore: match svelte and kit eslint config

### PR DESCRIPTION
**Pull request by benmccann**
the `node:` prefix is supported in the same versions of Node that `vite-plugin-svelte` supports: https://2ality.com/2021/12/node-protocol-imports.html#support-for-node%3A-imports

### CODE REVIEW

**Comment by dominikg** [comment]
adding the node: prefix is nice, but is there a benefit for the quote rule? prettier single is already active.

**Comment by benmccann** [comment]
prettier single will only change double quotes to single quotes, but it won't change unnecessary backticks to single quotes. I personally find it harder to read backticks because I often assume there's a variable nested within them and then I waste time looking for it, when it may not exist

you could change `pnpm fixup` to run `eslint --fix` and then it'd get handled automatically

**Comment by dominikg** [comment]
fixup runs both lint and fornat already

**Comment by benmccann** [comment]
strings are also better for performance than template literals

[benchmark](https://perf.link/#eyJpZCI6ImlyZm02d3FyOHFrIiwidGl0bGUiOiJTdHJpbmdzIHZzIHRlbXBsYXRlIGxpdGVyYWxzIiwiYmVmb3JlIjoiIiwidGVzdHMiOlt7Im5hbWUiOiJzdHJpbmdzIiwiY29kZSI6IidhJyArICdiJyIsInJ1bnMiOlszMTY1MDAwLDU3OTYwMDAsMzA0MjAwMCwyMzU5MDAwLDQwMjcwMDAsMTgxODAwMCwzNjA0MDAwLDE4NzAwMDAsNDM0MzAwMCw2OTYzMDAwLDg3MDAwLDkyMjAwMCw3ODk4MDAwLDUxNTIwMDAsMzkyMDAwMCwxNDk5MDAwLDk2MDMwMDAsNDc1OTAwMCw0ODQwMDAwLDg0NTQwMDAsNDM5MzAwMCw4NTI1MDAwLDU3ODMwMDAsNzUwMzAwMCw2MDU2MDAwLDc1MjcwMDAsMzE5NTAwMCw1NDA1MDAwLDc4MDAwLDYyMjMwMDAsMzY5NzAwMCw2MTQ3MDAwLDI1MDcwMDAsODIzMzAwMCw3NjEzMDAwLDEzNDIwMDAsNzk2NjAwMCw0MDA5MDAwLDgwOTAwMCw1MjAzMDAwLDMyOTYwMDAsNDQwNzAwMCwxNzk2MDAwLDM5MzcwMDAsMjE4MjAwMCwyNTg5MDAwLDIzMjAwMCw4OTU0MDAwLDU0MzgwMDAsNzA2NTAwMCwyNDg2MDAwLDIyNzIwMDAsOTQ0OTAwMCwyMjcyMDAwLDY2MzAwMCw1ODQxMDAwLDY4MDcwMDAsNTM2NDAwMCw3OTUwMDAsNDEzMDAwMCw4MDQ4MDAwLDI5MTUwMDAsNjEyODAwMCw3OTM5MDAwLDUyMTgwMDAsNzY0ODAwMCw4MDU2MDAwLDU0MTcwMDAsNzQyNjAwMCw2MDQ3MDAwLDY1MjcwMDAsNDU3ODAwMCw1MzU4MDAwLDg1MTAwMDAsNzQ4MTAwMCw3MDg4MDAwLDE5NDkwMDAsNzIzNTAwMCw3MjM0MDAwLDg4OTAwMCw1NTMyMDAwLDgwODAwMDAsNjE0MTAwMCw4MDc3MDAwLDQ1NDcwMDAsNDk0NTAwMCw0NDEwMDAsMzg2NjAwMCwxMjQ4MDAwLDUyMjgwMDAsMTA0MDAwMCw2MDUwMDAwLDczMjEwMDAsODU1NTAwMCwzMzIxMDAwLDU0MTgwMDAsODIzMzAwMCwyMTY5MDAwLDI2MzAwMCwzNzM1MDAwXSwib3BzIjo0ODIyMTEwfSx7Im5hbWUiOiJ0ZW1wbGF0ZSBsaXRlcmFscyIsImNvZGUiOiJgYWAgKyBgYmAiLCJydW5zIjpbMjM4ODAwMCwzOTYzMDAwLDE2NTYwMDAsMjQzMDAwLDEzNzAwMCwxOTk5MDAwLDIxMDEwMDAsNTIwNTAwMCwxOTUwMDAsODEwODAwMCw4NjAwMCwxNzQwMDAsNTkxNDAwMCwxOTI0MDAwLDQzMDAwLDMyNzYwMDAsODQ5MzAwMCw1NTcwMDAsMjgwMDAwMCwyODkzMDAwLDM1NDcwMDAsODI4MTAwMCwxMjU0MDAwLDU5NTAwMDAsNTc3MDAwMCwyODkxMDAwLDIxMTAwMCwyNDgwMDAsODcwMDAsNjg3MjAwMCwyNjEwMDAwLDE3OTQwMDAsMzI5NjAwMCw0ODkwMDAwLDc2OTMwMDAsNzIxNzAwMCw4MTY3MDAwLDMwNTIwMDAsNTQ2NjAwMCw1NDA5MDAwLDcxMDMwMDAsMjU1NDAwMCw3NDM0MDAwLDEyOTQwMDAsMTA5MDAwLDE0MDEwMDAsMzIzOTAwMCw5MjkyMDAwLDM0NzYwMDAsMjMyMDAwMCwyMDExMDAwLDIyNzgwMDAsMzg4MTAwMCw3NTcxMDAwLDI3NTQwMDAsMjkwODAwMCwyMjc0MDAwLDU2MDUwMDAsNzk4MDAwLDMwMjAwMDAsODA4OTAwMCw1OTM5MDAwLDI5NzYwMDAsMjQ3OTAwMCw0MjE3MDAwLDE2NTgwMDAsMjYxNzAwMCwxOTA5MDAwLDc0ODUwMDAsNjcwOTAwMCwzNjUzMDAwLDE0NjAwMCwxNjAxMDAwLDEzMjIwMDAsMTY3NDAwMCw0OTcwMDAwLDQ1NTAwMDAsNDQ4NTAwMCw1NzMwMDAwLDYxNDAwMDAsNjE2MjAwMCwzNDcxMDAwLDYwMDAwLDc2MTkwMDAsNDg2NjAwMCw0OTM2MDAwLDE0NjgwMDAsNDYxNzAwMCwzODgzMDAwLDQzMzEwMDAsNjAyMDAwLDY4MTgwMDAsNjk2NjAwMCwxMDYzMDAwLDg0NjMwMDAsNjM2ODAwMCw0ODc1MDAwLDQ5NjcwMDAsMTUyMDAwLDc2NzMwMDBdLCJvcHMiOjM3NTg5MTB9XSwidXBkYXRlZCI6IjIwMjMtMDgtMjNUMDA6NTk6NTguMDg1WiJ9)

**Review by bluwy — APPROVED** [review]

**Pull request merged**
